name: apis_with_serverpod_server
description: Starting point for a Serverpod server.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  serverpod: 2.0.2

dev_dependencies:
  lints: '>=3.0.0 <5.0.0'
